# Generated by Django 5.1.5 on 2025-01-24 20:11

import estantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='conteudo_html',
            field=models.FileField(upload_to=estantes.models.upload_to),
        ),
    ]
