# Generated by Django 5.1.5 on 2025-01-24 23:13

import estantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0002_alter_documento_conteudo_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=estantes.models.upload_to),
        ),
    ]
