# Generated by Django 5.1.5 on 2025-01-25 18:57

import estantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0004_alter_documento_autor_alter_documento_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='capa',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=estantes.models.upload_to),
        ),
    ]
