# Generated by Django 5.1.5 on 2025-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0005_alter_documento_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcacao',
            name='documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Marcacao',
        ),
    ]
