# Generated by Django 5.1.5 on 2025-01-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0006_remove_marcacao_documento_documento_ordem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['ordem']},
        ),
    ]
