# Generated by Django 5.1.5 on 2025-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estantes', '0007_alter_documento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='paginaatual',
            field=models.IntegerField(default=0),
        ),
    ]
